"""T048 — FR-028 / FR-031 privacy invariants for AI race narratives.

Scope covered by this module
-----------------------------
Three scopes defined in spec.md US6 / FR-027..FR-028 / FR-031:

  Round scope  — ``_analyst_agent_v2`` (nodo grafo) + ``invoke_per_valida``
  Season scope — ``invoke_season_summary``
  Club scope   — ``fetch_club_insights_by_race`` / club-insights router
                 (reads already-stored per-athlete insights; no new generation)

Coverage audit vs. existing tests
-----------------------------------
The following contracts are already green and are NOT duplicated here (see
docstring references):

* ``test_anonymize.py::test_anonymize_node_filters_real_athlete_id``
  — the ``anonymize`` node never puts ``athlete_id`` in ``anonymized_data``.
* ``test_anonymize.py::test_anonymize_sentinel_no_real_tyr_names_in_events``
  — state["events"] after anonymize contains no known TyR names.
* ``test_guardrails_race_v2_n1.py::TestVetoN1``
  — ``Guardrails(use_case="race_analyst_v2", forbidden_names=[...])`` scrubs
  names via ``build_race_v2_forbidden_names_rules``.
* ``test_invariants_v2.py`` Bloque 4/5
  — response serialization never exposes ``competitor_id`` of third parties.
* ``test_analyst_agent_v2_uses_full_season.py``
  — ``forbidden_names`` kwarg is propagated from state to ``invoke_per_valida``.

What this module ADDS (T048)
------------------------------
1. ``TestRoundScopeNameScrubbing`` — a fake LLM that emits the real minor's
   name inside the narrative. Asserts the final ``AnalysisOutput.raw_markdown``
   does NOT contain that name after guardrails run. Covers FR-028 for the
   round/per-valida path.

2. ``TestSeasonScopeNameScrubbing`` — same pattern for ``invoke_season_summary``.
   Also asserts that calling ``invoke_season_summary`` with
   ``forbidden_names=[]`` (the global/season contract: no individual is being
   analysed, so the caller passes an empty list to force fully anonymous
   wording) returns output that happens to be clean by construction — and that
   the guardrails instance is built with the empty list (not None, which would
   silently skip the rule).

3. ``TestSeasonScopeForbiddenNamesIsEmpty`` — property-style: when
   ``forbidden_names=[]`` is passed explicitly, the guardrail does NOT apply
   name-substitution rules (no rules are generated by
   ``build_race_v2_forbidden_names_rules``), so a truly anonymous narrative
   (all pseudonyms) passes cleanly, which is the documented expected behaviour
   for global/season views that aggregate across all athletes.

4. ``TestClubScopeParentMasking`` — asserts that the club-insights response
   masks the real name and ``summary_excerpt`` for athletes who are NOT the
   parent's own child.  No new narrative is generated in this scope; the
   privacy guarantee is enforced by the router layer.

Legal basis: Ley 1581/2012 Art. 3 (Colombia) — datos sensibles de menores.
"""

from __future__ import annotations

import unicodedata
from typing import Any

import pytest

from app.services.ai.guardrails import Guardrails, build_race_v2_forbidden_names_rules
from app.services.race.agents.analyst import (
    PROMPT_VERSION_ANALYST_V2,
    RaceAnalystAgent,
)
from app.services.race.schemas import AnalysisInput, LTADGroup, RunMetrics


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


_SEEDED_MINOR_NAME = "Valentina"
_SEEDED_MINOR_FULL_NAME = "Valentina Ficticia Ramos"


def _normalize(text: str) -> str:
    """Lower + strip accents for case/diacritic-insensitive substring check."""
    nfkd = unicodedata.normalize("NFKD", text.lower())
    return "".join(c for c in nfkd if unicodedata.category(c) != "Mn")


def _name_in_text(name: str, text: str) -> bool:
    """True if *name* (or any token of *name* ≥5 chars) appears in *text*."""
    norm_text = _normalize(text)
    for token in name.split():
        if len(token) >= 5 and _normalize(token) in norm_text:
            return True
    # Also check the whole name as a substring.
    return _normalize(name) in norm_text


def _make_analysis_input(pseudonym: str = "AzulZorro") -> AnalysisInput:
    return AnalysisInput(
        athlete_pseudonym=pseudonym,
        age=13,
        ltad_group=LTADGroup.JUVENIL,
        progression_df_records=[
            {"valida_num": 1, "position": 4, "race_time_ms": 2_000_000},
        ],
        podium_context={},
        memory_recent_insights=[],
        principles_citations=[],
        explain_mode=False,
        athlete_id=999,
        season=2026,
    )


def _make_zero_metrics() -> RunMetrics:
    return RunMetrics(
        tokens_in=10,
        tokens_out=20,
        latency_ms=5,
        cost_usd=0.0001,
        prompt_version=PROMPT_VERSION_ANALYST_V2,
    )


# ---------------------------------------------------------------------------
# Fake LLM helpers
# ---------------------------------------------------------------------------


class _FakeLLMCallResult:
    """Mimics ``LLMCallResult`` used inside ``_invoke_single_v2``."""

    def __init__(self, text: str) -> None:
        self.text = text
        self.tokens_in = 10
        self.tokens_out = 20
        self.latency_ms = 5
        self.cost_usd = 0.0


def _narrative_with_name(name: str) -> str:
    """Returns a well-formed v2 markdown that contains *name*."""
    return (
        f"## Qué pasó en esta válida\n"
        f"La deportista {name} compitió con determinación.\n\n"
        f"## Recorrido hasta acá\n"
        f"Con una sola válida disputada aún no es posible establecer una tendencia de progresión.\n\n"
        f"## Hacia dónde va\n"
        f"Reforzar técnica de descenso (categoría=technique, prioridad=med) [1].\n"
    )


# ---------------------------------------------------------------------------
# 1. Round scope — ``_analyst_agent_v2`` guardrail scrubs name in narrative
# ---------------------------------------------------------------------------


class TestRoundScopeNameScrubbing:
    """FR-028: round-scope narrative never contains a minor's name.

    Uses a fake ``RaceAnalystAgent`` whose ``invoke_per_valida`` calls the
    real ``_invoke_single_v2`` logic but injects a fake LLM that emits the
    seeded minor's real name. The test asserts that after guardrails the
    ``raw_markdown`` does NOT contain that name.

    We monkey-patch at the ``call_llm`` level inside the agent module so the
    real scrubbing pipeline (guardrails → report) runs unchanged.
    """

    @pytest.mark.asyncio
    async def test_round_narrative_scrubs_forbidden_name(self, monkeypatch):
        """Guardrail removes the minor's name from the round narrative."""
        import app.services.race.agents.analyst as analyst_mod

        dirty_text = _narrative_with_name(_SEEDED_MINOR_NAME)

        async def _fake_call_llm(llm, prompt):
            return _FakeLLMCallResult(dirty_text)

        monkeypatch.setattr(analyst_mod, "call_llm", _fake_call_llm)
        monkeypatch.setattr(analyst_mod, "build_chat_llm", lambda: None)

        agent = RaceAnalystAgent(prompt_version=PROMPT_VERSION_ANALYST_V2)
        inp = _make_analysis_input()
        results = await agent.invoke_per_valida(
            [(1, inp)],
            forbidden_names=[_SEEDED_MINOR_NAME, _SEEDED_MINOR_FULL_NAME],
            is_first_in_season=True,
        )

        output, _ = results[1]
        raw = output.raw_markdown or ""
        assert not _name_in_text(_SEEDED_MINOR_NAME, raw), (
            f"PRIVACY VIOLATION (FR-028, round scope): real minor name "
            f"'{_SEEDED_MINOR_NAME}' still present in narrative after "
            f"guardrails scrubbing.\nraw_markdown={raw!r}"
        )

    @pytest.mark.asyncio
    async def test_round_narrative_pseudonym_still_present_after_scrub(self, monkeypatch):
        """The pseudonym replaces the name — narrative is not empty after scrub."""
        import app.services.race.agents.analyst as analyst_mod

        dirty_text = _narrative_with_name(_SEEDED_MINOR_NAME)

        async def _fake_call_llm(llm, prompt):
            return _FakeLLMCallResult(dirty_text)

        monkeypatch.setattr(analyst_mod, "call_llm", _fake_call_llm)
        monkeypatch.setattr(analyst_mod, "build_chat_llm", lambda: None)

        agent = RaceAnalystAgent(prompt_version=PROMPT_VERSION_ANALYST_V2)
        inp = _make_analysis_input()
        results = await agent.invoke_per_valida(
            [(1, inp)],
            forbidden_names=[_SEEDED_MINOR_NAME],
            is_first_in_season=True,
        )
        output, _ = results[1]
        raw = output.raw_markdown or ""
        # The narrative must still have some content (not blanked out).
        assert len(raw.strip()) > 20, (
            "Narrative was completely wiped after scrubbing — "
            "guardrail should replace with 'la deportista', not blank."
        )

    @pytest.mark.asyncio
    async def test_round_scope_forbidden_names_propagated_from_state(self):
        """``_analyst_agent_v2`` reads ``forbidden_names`` from state and
        passes it to ``invoke_per_valida``.

        Cross-reference: ``test_analyst_agent_v2_uses_full_season.py``
        already verifies this via ``_RecordingAgent``. This test adds the
        assertion at the *guardrail layer*: if the state forbids a name, the
        agent call actually carries it.
        """
        from app.services.race.ai.nodes.analyst_agent import _analyst_agent_v2

        received_forbidden: list[list[str]] = []

        class _SpyAgent:
            async def invoke_per_valida(
                self,
                pairs: list,
                *,
                forbidden_names: list[str] | None = None,
                **kwargs: Any,
            ) -> dict:
                received_forbidden.append(list(forbidden_names or []))
                from tests.services.race.ai.conftest import (
                    make_analysis_output,
                    make_zero_metrics,
                )
                return {
                    vn: (make_analysis_output(), make_zero_metrics("race_analyst_v2"))
                    for vn, _ in pairs
                }

        state = {
            "athlete_id": 1,
            "season": 2026,
            "athlete_age": 13,
            "ltad_group": "juvenil",
            "anonymized_data": {"pseudonym": "AzulZorro"},
            "metrics": {"progression": [{"valida_num": 1, "position": 4}]},
            "podium_context": {},
            "principles": [],
            "memory": [],
            "forbidden_names": [_SEEDED_MINOR_NAME, _SEEDED_MINOR_FULL_NAME],
            "valida_nums": [1],
            "prompt_version": PROMPT_VERSION_ANALYST_V2,
            "is_first_in_season": True,
            "full_season_results": [],
            "_analyst_agent": _SpyAgent(),
        }
        await _analyst_agent_v2(state)

        assert received_forbidden, "invoke_per_valida was never called"
        assert _SEEDED_MINOR_NAME in received_forbidden[0], (
            f"FR-028/FR-031: forbidden_names from state not passed to "
            f"invoke_per_valida. Received: {received_forbidden[0]!r}"
        )


# ---------------------------------------------------------------------------
# 2. Season scope — ``invoke_season_summary`` scrubs name + empty list contract
# ---------------------------------------------------------------------------


class TestSeasonScopeNameScrubbing:
    """FR-028: season-scope narrative never contains a minor's name.

    ``invoke_season_summary`` is called with ``forbidden_names=[name]`` and
    a fake LLM that emits the name. Asserts output is clean.
    """

    @pytest.mark.asyncio
    async def test_season_narrative_scrubs_forbidden_name(self, monkeypatch):
        """Season summary guardrail removes the minor's name."""
        import app.services.race.agents.analyst as analyst_mod

        dirty_text = (
            f"## Resumen de temporada\n"
            f"La deportista {_SEEDED_MINOR_NAME} tuvo una temporada de aprendizaje.\n"
            f"Progresó en técnica de descenso.\n"
        )

        async def _fake_call_llm(llm, prompt):
            return _FakeLLMCallResult(dirty_text)

        monkeypatch.setattr(analyst_mod, "call_llm", _fake_call_llm)
        monkeypatch.setattr(analyst_mod, "build_chat_llm", lambda: None)

        agent = RaceAnalystAgent(prompt_version=PROMPT_VERSION_ANALYST_V2)
        inp = _make_analysis_input()
        output, _ = await agent.invoke_season_summary(
            inp,
            forbidden_names=[_SEEDED_MINOR_NAME, _SEEDED_MINOR_FULL_NAME],
        )

        raw = output.raw_markdown or ""
        assert not _name_in_text(_SEEDED_MINOR_NAME, raw), (
            f"PRIVACY VIOLATION (FR-028, season scope): real minor name "
            f"'{_SEEDED_MINOR_NAME}' still present in season summary after "
            f"guardrails.\nraw_markdown={raw!r}"
        )

    @pytest.mark.asyncio
    async def test_season_narrative_scrubs_full_name(self, monkeypatch):
        """Season summary guardrail removes the full multi-token real name."""
        import app.services.race.agents.analyst as analyst_mod

        dirty_text = (
            f"## Resumen de temporada\n"
            f"La deportista {_SEEDED_MINOR_FULL_NAME} cerró la temporada en buena forma.\n"
        )

        async def _fake_call_llm(llm, prompt):
            return _FakeLLMCallResult(dirty_text)

        monkeypatch.setattr(analyst_mod, "call_llm", _fake_call_llm)
        monkeypatch.setattr(analyst_mod, "build_chat_llm", lambda: None)

        agent = RaceAnalystAgent(prompt_version=PROMPT_VERSION_ANALYST_V2)
        inp = _make_analysis_input()
        output, _ = await agent.invoke_season_summary(
            inp,
            forbidden_names=[_SEEDED_MINOR_FULL_NAME],
        )

        raw = output.raw_markdown or ""
        for token in _SEEDED_MINOR_FULL_NAME.split():
            if len(token) >= 5:
                assert not _name_in_text(token, raw), (
                    f"PRIVACY VIOLATION (FR-028, season scope): token "
                    f"'{token}' from real name still in season summary.\n"
                    f"raw_markdown={raw!r}"
                )


# ---------------------------------------------------------------------------
# 3. Season/global scope — ``forbidden_names=[]`` forces anonymous wording
# ---------------------------------------------------------------------------


class TestSeasonScopeForbiddenNamesIsEmpty:
    """FR-028 / FR-031: when ``forbidden_names=[]`` the name-substitution
    rules are NOT generated (``build_race_v2_forbidden_names_rules`` with an
    empty list returns an empty tuple), so the narrative is expected to already
    be fully anonymous.

    This is the documented contract for *global/season* views that aggregate
    across all athletes and have no single-athlete personal data to protect.
    The LLM receives only a pseudonym; the guardrail receives an empty list
    because there is no specific minor to protect at this aggregate level.
    """

    def test_empty_forbidden_names_generates_no_name_rules(self):
        """``build_race_v2_forbidden_names_rules([])`` returns an empty tuple.

        This is the foundation of the global/season contract: passing an empty
        list MUST produce zero regex rules so the guardrail does not attempt
        name substitution on an underpopulated rule set.
        """
        rules = build_race_v2_forbidden_names_rules([])
        assert rules == (), (
            "build_race_v2_forbidden_names_rules([]) must return () — "
            "no rules generated for the global/season anonymous path."
        )

    def test_guardrails_with_empty_list_does_not_scrub_pseudonym(self):
        """A narrative that uses only pseudonyms passes cleanly when
        ``forbidden_names=[]``.

        Cross-reference: ``test_invariants_v2.py::TestAgeMismatchKwarg`` and
        ``test_guardrails_race_v2_n1.py::TestVetoN1`` already verify veto
        rules; this test specifically validates the name-substitution path
        is correctly a no-op for the empty-list season/global contract.
        """
        g = Guardrails(use_case="race_analyst_v2", forbidden_names=[])
        # Narrative uses only the pseudonym — no real name present.
        clean_text = (
            "## Qué pasó en esta válida\n"
            "La deportista participó con buen ritmo en la categoría infantil.\n\n"
            "## Recorrido hasta acá\n"
            "Con una sola válida disputada aún no es posible establecer "
            "una tendencia de progresión.\n\n"
            "## Hacia dónde va\n"
            "Reforzar técnica de frenada (categoría=technique, prioridad=med) [1].\n"
        )
        report = g.scrub_with_report(clean_text)
        name_violations = [
            v for v in report.violations
            if v.startswith("forbidden_name_")
        ]
        assert name_violations == [], (
            "No forbidden_name_* violations expected when forbidden_names=[].\n"
            f"Got: {name_violations!r}"
        )

    @pytest.mark.asyncio
    async def test_season_summary_with_empty_forbidden_names_succeeds(self, monkeypatch):
        """``invoke_season_summary(forbidden_names=[])`` completes without error.

        Documents that the global/season path explicitly passes an empty list
        (not None) and that this does not trigger any exception or implicit
        name-rule generation.
        """
        import app.services.race.agents.analyst as analyst_mod

        anonymous_text = (
            "## Resumen de temporada\n"
            "La temporada mostró participación activa en la categoría infantil. "
            "La progresión por resultados fue constante.\n"
        )

        async def _fake_call_llm(llm, prompt):
            return _FakeLLMCallResult(anonymous_text)

        monkeypatch.setattr(analyst_mod, "call_llm", _fake_call_llm)
        monkeypatch.setattr(analyst_mod, "build_chat_llm", lambda: None)

        agent = RaceAnalystAgent(prompt_version=PROMPT_VERSION_ANALYST_V2)
        inp = _make_analysis_input(pseudonym="Atleta-0144-T2026")
        # Passing [] explicitly (not None) is the documented global/season contract.
        output, metrics = await agent.invoke_season_summary(
            inp,
            forbidden_names=[],  # empty list = no individual to protect
        )

        assert output is not None
        assert (output.raw_markdown or "") != "", (
            "Season summary must not return empty markdown when anonymous text is clean."
        )
        # No real name in output — sanity check.
        assert not _name_in_text(_SEEDED_MINOR_NAME, output.raw_markdown or "")


# ---------------------------------------------------------------------------
# 4. Club scope — parent masking for non-child athletes
# ---------------------------------------------------------------------------


class TestClubScopeParentMasking:
    """FR-028 / FR-030: club-insights response masks names and summary for
    athletes who are NOT the requesting parent's own child.

    The club-insights router does NOT generate new narratives — it reads
    already-persisted per-athlete insights. Privacy is enforced at the router
    layer via ``_build_item_parent_other`` which replaces:
      * ``athlete_display_name`` → "[Atleta del club]"
      * ``summary_excerpt``      → None
      * ``athlete_id``           → 0  (non-navigable)
      * ``confidence``           → None

    This test uses the router helper functions directly (unit level) to avoid
    needing a full HTTP stack, while the integration contract is covered by
    ``test_race_analysis_privacy.py``.
    """

    def test_parent_other_item_does_not_contain_athlete_name(self):
        """``_build_item_parent_other`` produces an item with masked name."""
        from app.routers.club_race_insights import _build_item_parent_other

        item = _build_item_parent_other(athlete_id=42, valida_num=1)

        assert item.athlete_id == 0, (
            "athlete_id must be 0 for other-child parent items "
            "(non-navigable — FR-030)"
        )
        assert "[Atleta" in item.athlete_display_name, (
            "athlete_display_name must be masked for non-child parent items "
            f"(got {item.athlete_display_name!r})"
        )
        assert item.summary_excerpt is None, (
            "summary_excerpt must be None for non-child parent items (FR-028)"
        )
        assert item.confidence is None, (
            "confidence must be None for parent callers (FR-030)"
        )

    def test_parent_other_item_never_contains_real_name(self):
        """The masked item does NOT contain any token of a seeded real name."""
        from app.routers.club_race_insights import _build_item_parent_other

        item = _build_item_parent_other(athlete_id=99, valida_num=2)
        # Serialise all string fields.
        all_text = " ".join(
            str(v) for v in [
                item.athlete_display_name,
                item.summary_excerpt,
            ]
            if v is not None
        )
        assert not _name_in_text(_SEEDED_MINOR_NAME, all_text), (
            f"PRIVACY VIOLATION (FR-028, club scope): real minor name token "
            f"found in parent-masked club item. all_text={all_text!r}"
        )

    def test_coach_item_builds_with_excerpt_and_name(self):
        """Coach item (non-masked) carries the display name and summary excerpt.

        Inverse contract: confirm the masking is only applied for parent role —
        coaches must still receive the data for their coaching work.
        """
        from app.routers.club_race_insights import _build_item_coach
        from app.models.athlete_ai_insight import InsightConfidence
        from datetime import datetime, timezone

        item = _build_item_coach(
            athlete_id=42,
            display_name=_SEEDED_MINOR_FULL_NAME,
            valida_num=1,
            insight_id=10,
            summary_text="Progreso en frenada.",
            generated_at=datetime.now(timezone.utc),
            confidence=InsightConfidence.medium,
        )

        assert item.athlete_display_name == _SEEDED_MINOR_FULL_NAME
        assert item.summary_excerpt is not None
        assert item.confidence is not None


# ---------------------------------------------------------------------------
# 5. Guardrail unit: forbidden_names word-boundary replaces, not blanks
# ---------------------------------------------------------------------------


class TestGuardrailForbiddenNamesUnit:
    """Unit tests for the ``forbidden_name_*`` rule produced by
    ``build_race_v2_forbidden_names_rules``.

    Cross-reference: ``test_guardrails_race_v2.py`` has the same contract
    marked xfail with the old API. Here we test the implemented API directly
    (the rules build function + Guardrails class), which is confirmed GREEN in
    ``test_guardrails_race_v2_n1.py``.
    """

    def test_forbidden_name_replaced_by_deportista(self):
        """A real name in the narrative is replaced with 'la deportista'."""
        g = Guardrails(
            use_case="race_analyst_v2",
            forbidden_names=[_SEEDED_MINOR_NAME],
        )
        text = (
            f"## Qué pasó en esta válida\n"
            f"La ciclista {_SEEDED_MINOR_NAME} hizo una gran carrera.\n\n"
            f"## Recorrido hasta acá\n"
            f"Con una sola válida disputada aún no es posible establecer "
            f"una tendencia de progresión.\n\n"
            f"## Hacia dónde va\n"
            f"Continuar entrenando técnica.\n"
        )
        report = g.scrub_with_report(text)

        # After scrubbing, the real name must be absent.
        assert _SEEDED_MINOR_NAME not in report.text, (
            f"Real name '{_SEEDED_MINOR_NAME}' still present after scrub.\n"
            f"scrubbed={report.text!r}"
        )
        # And at least one forbidden_name_* violation was recorded.
        assert any(v.startswith("forbidden_name_") for v in report.violations), (
            f"Expected a forbidden_name_* violation. Got: {report.violations!r}"
        )

    def test_forbidden_name_case_insensitive(self):
        """Name match is case-insensitive (Ley 1581 — no bypass via casing)."""
        g = Guardrails(
            use_case="race_analyst_v2",
            forbidden_names=[_SEEDED_MINOR_NAME],
        )
        text = (
            "## Qué pasó en esta válida\n"
            "VALENTINA compitió bien.\n\n"
            "## Recorrido hasta acá\n"
            "Con una sola válida disputada aún no es posible establecer "
            "una tendencia de progresión.\n\n"
            "## Hacia dónde va\n"
            "Técnica de frenada.\n"
        )
        report = g.scrub_with_report(text)

        assert _SEEDED_MINOR_NAME.upper() not in report.text
        assert "valentina" not in report.text.lower(), (
            "Case-insensitive match failed: uppercase variant still present."
        )

    def test_forbidden_name_empty_list_no_violation(self):
        """``forbidden_names=[]`` produces zero name-substitution rules —
        passing a narrative with a name does NOT trigger a violation.

        This is the documented global/season contract: the caller explicitly
        opts out of per-athlete name protection when processing aggregate data.
        A real name should not appear in an aggregate narrative by construction
        (the prompt only receives pseudonyms), but even if it did, the empty
        list contract means NO name rules are installed.
        """
        g = Guardrails(use_case="race_analyst_v2", forbidden_names=[])
        text = (
            "## Qué pasó en esta válida\n"
            "La deportista participó activamente.\n\n"
            "## Recorrido hasta acá\n"
            "Con una sola válida disputada aún no es posible establecer "
            "una tendencia de progresión.\n\n"
            "## Hacia dónde va\n"
            "Técnica de descenso.\n"
        )
        report = g.scrub_with_report(text)
        name_violations = [v for v in report.violations if v.startswith("forbidden_name_")]
        assert name_violations == [], (
            "With forbidden_names=[], no name-substitution rules should fire.\n"
            f"violations={name_violations!r}"
        )
