"""agrega tablas training_session, session_attendance, monthly_report

Revision ID: 6e189a7e1e51
Revises: f3a4b5c6d7e8
Create Date: 2026-05-06 17:30:57.896632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e189a7e1e51'
down_revision: Union[str, None] = 'f3a4b5c6d7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('metrics_snapshot', sa.JSON(), nullable=True),
    sa.Column('generated_by_user_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'year', 'month', name='uq_monthly_report_period')
    )
    op.create_table('training_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'executed', 'cancelled', name='sessionstatus'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_start_time', sa.Time(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('technical_focus', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('route_text', sa.Text(), nullable=True),
    sa.Column('strava_url', sa.String(length=500), nullable=True),
    sa.Column('route_file_path', sa.String(length=500), nullable=True),
    sa.Column('coach_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('duration_min BETWEEN 15 AND 240', name='ck_session_duration_range'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_training_session_club_date', 'training_sessions', ['club_id', 'scheduled_date'], unique=False)
    op.create_table('session_attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('presente', 'ausente', 'justificado', 'tarde', 'lesionado', name='attendancestatus'), nullable=False),
    sa.Column('excuse_reason', sa.String(length=300), nullable=True),
    sa.Column('rpe_omni', sa.Integer(), nullable=True),
    sa.Column('rubric_effort', sa.Integer(), nullable=True),
    sa.Column('rubric_attitude', sa.Integer(), nullable=True),
    sa.Column('rubric_technique', sa.Integer(), nullable=True),
    sa.Column('individual_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rpe_omni BETWEEN 0 AND 10 OR rpe_omni IS NULL', name='ck_attendance_rpe_range'),
    sa.CheckConstraint('rubric_attitude BETWEEN 1 AND 5 OR rubric_attitude IS NULL', name='ck_attendance_rubric_attitude_range'),
    sa.CheckConstraint('rubric_effort BETWEEN 1 AND 5 OR rubric_effort IS NULL', name='ck_attendance_rubric_effort_range'),
    sa.CheckConstraint('rubric_technique BETWEEN 1 AND 5 OR rubric_technique IS NULL', name='ck_attendance_rubric_technique_range'),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'athlete_id', name='uq_session_attendance')
    )
    op.create_index('idx_session_attendance_athlete_created', 'session_attendance', ['athlete_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_session_attendance_athlete_created', table_name='session_attendance')
    op.drop_table('session_attendance')
    op.drop_index('idx_training_session_club_date', table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_table('monthly_reports')
    # ### end Alembic commands ###
