"""add_ai_explanations_cache

Revision ID: 786202a460c1
Revises: b54b6273ce1f
Create Date: 2026-05-05 20:03:32.171300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786202a460c1'
down_revision: Union[str, None] = 'b54b6273ce1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete_ai_explanations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('anthropometric_record_id', sa.Integer(), nullable=False),
    sa.Column('use_case', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('age_group', sa.String(length=16), nullable=False),
    sa.Column('maturation_status', sa.String(length=32), nullable=False),
    sa.Column('generated_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['anthropometric_record_id'], ['anthropometric_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'anthropometric_record_id', 'use_case', name='uq_ai_expl_athlete_record_usecase')
    )
    op.create_index('ix_ai_expl_athlete_id', 'athlete_ai_explanations', ['athlete_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_expl_athlete_id', table_name='athlete_ai_explanations')
    op.drop_table('athlete_ai_explanations')
    # ### end Alembic commands ###
