"""agrega tabla parental_consents

Revision ID: b54b6273ce1f
Revises: c3d4e5f6a7b8
Create Date: 2026-04-15 18:16:26.527508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54b6273ce1f'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parental_consents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_user_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('consent_version', sa.String(length=20), nullable=False),
    sa.Column('consented_at', sa.DateTime(), nullable=False),
    sa.Column('consent_method', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('data_collection', sa.Boolean(), nullable=False),
    sa.Column('training_tracking', sa.Boolean(), nullable=False),
    sa.Column('anthropometry', sa.Boolean(), nullable=False),
    sa.Column('third_party_sharing', sa.Boolean(), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parental_consents_athlete_id', 'parental_consents', ['athlete_id'], unique=False)
    op.create_index('ix_parental_consents_parent_athlete', 'parental_consents', ['parent_user_id', 'athlete_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_parental_consents_parent_athlete', table_name='parental_consents')
    op.drop_index('ix_parental_consents_athlete_id', table_name='parental_consents')
    op.drop_table('parental_consents')
    # ### end Alembic commands ###
